/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasAttr: typeof import('./components/CanvasAttr.vue')['default']
    ComponentAttrPanel: typeof import('./components/ComponentAttrPanel.vue')['default']
    ComponentList: typeof import('./components/ComponentList.vue')['default']
    ContextMenu: typeof import('./components/editor/ContextMenu.vue')['default']
    Editor: typeof import('./components/editor/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Grid: typeof import('./components/editor/Grid.vue')['default']
    MarkLine: typeof import('./components/editor/MarkLine.vue')['default']
    Preview: typeof import('./components/preview/Preview.vue')['default']
    PreviewNode: typeof import('./components/preview/PreviewNode.vue')['default']
    RealTimeComponentList: typeof import('./components/RealTimeComponentList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shape: typeof import('./components/editor/Shape.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}
